### ISSUE TITLE
Command import

### ISSUE THREAD

**Issue by LeniLeGoff** [fredokun/MrPython#10]
Command import, in the command prompt, conduct to a syntax error : 

```
=== Evaluating: 'import math'  === 
Error==> SyntaxError: invalid syntax (<string>, line 1)
===================================
```

**Comment by fredokun** [comment]
import math is not an expression ...
The "solution" is to create a new file,   write import math and execute it.

**Comment by LeniLeGoff** [comment]
Ok, but in classical Python command prompt, "import" work well.

**Comment by fredokun** [comment]
you're right, but the purpose of the "eval zone" of MrPython is just
to be able to evaluate expressions in connection with the editor buffer
(similarly to DrRacket if you know it)...

But I could allow any python statements (using `exec` and getting the value
of the last expression, if any, instead of relying of `eval`)...
That's just a little bit too much work for now.

So let's label this as an enhancement too.

and thank you for the feedback
